import os
import ssl
import urllib.request
import json
import re

# Create unverified SSL context just in case
ssl_context = ssl._create_unverified_context()

PRODUCTS = [
    {
        "id": 1,
        "name": "Colombia Antioquia (8oz)",
        "slug": "colombia-antioquia",
        "pack_size": "8oz",
        "category_name": "Rich & Smooth",
        "category_slug": "rich-smooth",
        "source_url": "https://www.coffeebean.pk/product/colombia-antioquia-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Colombia-Antioquia-8oz-550x550.jpg",
        "local_image": "/products/coffee/colombia-antioquia.jpg",
        "filename": "colombia-antioquia.jpg",
        "roast_level": "Medium Roast",
        "origin": "Antioquia, Colombia",
        "flavor_profile": "Plum aroma with hints of mandarin & milk chocolate. A smooth walnut finish.",
        "description": "Plum aroma with hints of mandarin & milk chocolate. A smooth walnut finish. Sourced from the Antioquia department of Colombia, known for producing some of the country's finest, most well-balanced high-altitude coffees.",
    },
    {
        "id": 2,
        "name": "100% Kona Coffee (8oz)",
        "slug": "kona-coffee",
        "pack_size": "8oz",
        "category_name": "Reserved",
        "category_slug": "reserved",
        "source_url": "https://www.coffeebean.pk/product/100-kona-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/100-Kona-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/kona-coffee.jpg",
        "filename": "kona-coffee.jpg",
        "roast_level": "Medium Roast",
        "origin": "Kona District, Hawaii",
        "flavor_profile": "Sweet floral aroma, jasmine nuances, subtle nutty overtones and a buttery finish.",
        "description": "100% pure authentic Kona coffee harvested from the volcanic slopes of Mauna Loa and Hualalai. Known globally for its silky body and delicate aromatic sweetness.",
    },
    {
        "id": 3,
        "name": "Papua New Guinea Sigri Coffee (8oz)",
        "slug": "papua-new-guinea-sigri",
        "pack_size": "8oz",
        "category_name": "Medium & Smooth",
        "category_slug": "medium-smooth",
        "source_url": "https://www.coffeebean.pk/product/papua-new-guinea-sigri-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Papua-New-Guinea-Sigri-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/papua-new-guinea-sigri.jpg",
        "filename": "papua-new-guinea-sigri.jpg",
        "roast_level": "Medium Roast",
        "origin": "Sigri Estate, Wahgi Valley, Papua New Guinea",
        "flavor_profile": "Delicate mango and herbal notes with vibrant honey sweetness and clean finish.",
        "description": "Sourced from the renowned Sigri Estate in the Wahgi Valley of Western Highlands. Exclusive Jamaican Blue Mountain typica cultivars grown in volcanic soils at 5,200 ft.",
    },
    {
        "id": 4,
        "name": "Mocha Java Coffee (8oz)",
        "slug": "mocha-java",
        "pack_size": "8oz",
        "category_name": "Medium & Smooth",
        "category_slug": "medium-smooth",
        "source_url": "https://www.coffeebean.pk/product/mocha-java-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Mocha-Java-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/mocha-java.jpg",
        "filename": "mocha-java.jpg",
        "roast_level": "Medium Roast",
        "origin": "Yemen & Indonesian Estate Blend",
        "flavor_profile": "Wild Arabian spice notes balanced by rich Indonesian dark chocolate body.",
        "description": "The world's oldest and most historic coffee blend. Combines exotic, winey Arabian Yemen Mocha beans with the heavy, syrupy depth of Indonesian Java Arabica.",
    },
    {
        "id": 5,
        "name": "Kenya AA Coffee (8oz)",
        "slug": "kenya-aa",
        "pack_size": "8oz",
        "category_name": "Medium & Smooth",
        "category_slug": "medium-smooth",
        "source_url": "https://www.coffeebean.pk/product/kenya-aa-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Kenya-AA-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/kenya-aa.jpg",
        "filename": "kenya-aa.jpg",
        "roast_level": "Medium Roast",
        "origin": "High-altitude slopes of Mt. Kenya",
        "flavor_profile": "Blackcurrant and citrus acidity with a savory, wine-like complex body.",
        "description": "Kenya AA represents the largest bean screen size and highest specialty grade in Kenyan coffee classification. Grown in nutrient-dense red volcanic soil above 5,500 ft.",
    },
    {
        "id": 6,
        "name": "Costa Rica La Cascada Tarrazu Coffee (8oz)",
        "slug": "costa-rica-la-cascada-tarrazu",
        "pack_size": "8oz",
        "category_name": "Medium & Smooth",
        "category_slug": "medium-smooth",
        "source_url": "https://www.coffeebean.pk/product/costa-rica-la-cascada-tarrazu-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Costa-Rica-La-Cascada-Tarrazu-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/costa-rica-la-cascada-tarrazu.jpg",
        "filename": "costa-rica-la-cascada-tarrazu.jpg",
        "roast_level": "Medium Roast",
        "origin": "Tarrazu Valley, Costa Rica",
        "flavor_profile": "Crisp green apple, milk chocolate undertones, and toasted almond finish.",
        "description": "Harvested from the legendary La Cascada estate in Costa Rica's Tarrazu mountain basin. Renowned for strict hard bean (SHB) density and immaculate flavor clarity.",
    },
    {
        "id": 7,
        "name": "Colombia Narino Coffee (8oz)",
        "slug": "colombia-narino",
        "pack_size": "8oz",
        "category_name": "Medium & Smooth",
        "category_slug": "medium-smooth",
        "source_url": "https://www.coffeebean.pk/product/colombia-narino-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Colombia-Narino-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/colombia-narino.jpg",
        "filename": "colombia-narino.jpg",
        "roast_level": "Medium Roast",
        "origin": "Nariño Department, Colombia",
        "flavor_profile": "Sugary caramel aroma, citrus brightness, and smooth toasted walnut body.",
        "description": "Grown in the dramatic steep canyons of Nariño near the equator at extreme elevations up to 6,500 ft, where warm canyon breezes shelter coffee trees during cold Andean nights.",
    },
    {
        "id": 8,
        "name": "House Blend Coffee (8oz)",
        "slug": "house-blend",
        "pack_size": "8oz",
        "category_name": "Light & Subtle",
        "category_slug": "light-subtle",
        "source_url": "https://www.coffeebean.pk/product/house-blend-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/House-Blend-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/house-blend.jpg",
        "filename": "house-blend.jpg",
        "roast_level": "Light Roast",
        "origin": "Specialty Latin American Blend",
        "flavor_profile": "Fragrant floral bouquet, light caramel sweetness, and crisp soothing finish.",
        "description": "The Coffee Bean & Tea Leaf's signature foundational blend created in 1963. Roasted gently to preserve the natural sweetness and delicate aromatics of Latin American coffees.",
    },
    {
        "id": 9,
        "name": "Brazil Cerrado Coffee (8oz)",
        "slug": "brazil-cerrado",
        "pack_size": "8oz",
        "category_name": "Light & Subtle",
        "category_slug": "light-subtle",
        "source_url": "https://www.coffeebean.pk/product/brazil-cerrado-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Brazil-Cerrado-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/brazil-cerrado.jpg",
        "filename": "brazil-cerrado.jpg",
        "roast_level": "Light Roast",
        "origin": "Cerrado Mineiro, Minas Gerais, Brazil",
        "flavor_profile": "Toasted hazelnut, sweet golden honey, and mild low-acid chocolate finish.",
        "description": "Naturally sun-dried pulped Arabica from the plateau savannahs of Cerrado Mineiro, delivering low acidity, creamy mouthfeel, and deep nuttiness.",
    },
    {
        "id": 10,
        "name": "Ethiopia Yirgacheffe Coffee (8oz)",
        "slug": "ethiopia-yirgacheffe",
        "pack_size": "8oz",
        "category_name": "Light & Distinctive",
        "category_slug": "light-distinctive",
        "source_url": "https://www.coffeebean.pk/product/ethiopia-yirgacheffe-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Ethiopia-Yirgacheffe-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/ethiopia-yirgacheffe.jpg",
        "filename": "ethiopia-yirgacheffe.jpg",
        "roast_level": "Light Roast",
        "origin": "Yirgacheffe, Sidamo, Southern Ethiopia",
        "flavor_profile": "Intense jasmine aroma, bergamot citrus, and honey tea-like finish.",
        "description": "Celebrated worldwide as the birthplace of Arabica coffee. Heirloom varietals wet-processed in clean mountain water yielding tea-like delicacy and intoxicating floral aromatics.",
    },
    {
        "id": 11,
        "name": "Hazelnut Coffee (12oz)",
        "slug": "hazelnut",
        "pack_size": "12oz",
        "category_name": "Flavoured Coffee",
        "category_slug": "flavoured-coffee",
        "source_url": "https://www.coffeebean.pk/product/hazelnut-coffee-12oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Hazelnut-Coffee-12oz-550x550.jpg",
        "local_image": "/products/coffee/hazelnut.jpg",
        "filename": "hazelnut.jpg",
        "roast_level": "Flavoured Roast",
        "origin": "Central & South American Specialty Beans",
        "flavor_profile": "Warm toasted Oregon hazelnuts and sweet creamy buttery finish.",
        "description": "Freshly roasted specialty 100% Arabica beans infused with natural rich toasted hazelnut oils. Delicious both hot and poured over ice with a splash of cream.",
    },
    {
        "id": 12,
        "name": "French Vanilla Coffee (12oz)",
        "slug": "french-vanilla",
        "pack_size": "12oz",
        "category_name": "Flavoured Coffee",
        "category_slug": "flavoured-coffee",
        "source_url": "https://www.coffeebean.pk/product/french-vanilla-coffee-12oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/French-Vanilla-Coffee-12oz-550x550.jpg",
        "local_image": "/products/coffee/french-vanilla.jpg",
        "filename": "french-vanilla.jpg",
        "roast_level": "Flavoured Roast",
        "origin": "Central & South American Specialty Beans",
        "flavor_profile": "Sweet Madagascar bourbon vanilla aroma with smooth creamy custard notes.",
        "description": "A customer favorite since the early 1970s. Premium whole bean Arabica blended with natural aromatic vanilla essence to create a silky, dessert-like coffee experience.",
    },
    {
        "id": 13,
        "name": "Decaf House Blend Coffee (8oz)",
        "slug": "decaf-house-blend",
        "pack_size": "8oz",
        "category_name": "Decaffeinated",
        "category_slug": "decaffeinated",
        "source_url": "https://www.coffeebean.pk/product/decaf-house-blend-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Decaf-House-Blend-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/decaf-house-blend.jpg",
        "filename": "decaf-house-blend.jpg",
        "roast_level": "Decaffeinated Light",
        "origin": "Latin America (Natural Decaf Process)",
        "flavor_profile": "Caramelized sugar, subtle apple sweetness, and clean smooth body without caffeine.",
        "description": "Naturally decaffeinated to gently remove 99.9% of caffeine while keeping intact the complete flavor spectrum, delicate floral notes, and body of our classic House Blend.",
    },
    {
        "id": 14,
        "name": "Decaf Espresso Roast Coffee (8oz)",
        "slug": "decaf-espresso-roast",
        "pack_size": "8oz",
        "category_name": "Decaffeinated",
        "category_slug": "decaffeinated",
        "source_url": "https://www.coffeebean.pk/product/decaf-espresso-roast-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Decaf-Espresso-Roast-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/decaf-espresso-roast.jpg",
        "filename": "decaf-espresso-roast.jpg",
        "roast_level": "Decaffeinated Dark",
        "origin": "Specialty Espresso Blend (Decaf)",
        "flavor_profile": "Dark bittersweet cocoa, smoky spice, and thick golden crema without caffeine.",
        "description": "Specially crafted for espresso lovers who want rich crema, intense body, and bold bittersweet chocolate extraction without caffeine.",
    },
    {
        "id": 15,
        "name": "Viennese Coffee (8oz)",
        "slug": "viennese",
        "pack_size": "8oz",
        "category_name": "Dark & Distinctive",
        "category_slug": "dark-distinctive",
        "source_url": "https://www.coffeebean.pk/product/viennese-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Viennese-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/viennese.jpg",
        "filename": "viennese.jpg",
        "roast_level": "Dark Roast",
        "origin": "European Roast Blend",
        "flavor_profile": "Dark baker's chocolate, spicy clove nuances, and velvety rich body.",
        "description": "Inspired by the classic grand cafes of Vienna. Roasted to the edge of darkness to yield an aromatic, full-bodied cup with deep spicy undertones.",
    },
    {
        "id": 16,
        "name": "Sumatra Mandheling Dark Coffee (8oz)",
        "slug": "sumatra-mandheling-dark",
        "pack_size": "8oz",
        "category_name": "Dark & Distinctive",
        "category_slug": "dark-distinctive",
        "source_url": "https://www.coffeebean.pk/product/sumatra-mandheling-dark-coffee-8oz/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Sumatra-Mandheling-Dark-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/sumatra-mandheling-dark.jpg",
        "filename": "sumatra-mandheling-dark.jpg",
        "roast_level": "Dark Roast",
        "origin": "Mount Leuser, Sumatra, Indonesia",
        "flavor_profile": "Earthy cedar aroma, dark cacao, syrupy heavy body, and low acidity.",
        "description": "Grown by smallholder farmers near Mount Leuser. Prepared using the traditional Giling Basah (wet-hulling) technique for an unmistakably heavy, complex, and earthy cup.",
    },
    {
        "id": 17,
        "name": "Sulawesi Toraja",
        "slug": "sulawesi-toraja",
        "pack_size": None, # Source title does not specify pack size; strictly preserving source data
        "category_name": "Dark & Distinctive",
        "category_slug": "dark-distinctive",
        "source_url": "https://www.coffeebean.pk/product/sulawesi-toraja/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Sulawesi-Toraja-550x550.jpg",
        "local_image": "/products/coffee/sulawesi-toraja.jpg",
        "filename": "sulawesi-toraja.jpg",
        "roast_level": "Dark Roast",
        "origin": "Toraja Highlands, Sulawesi, Indonesia",
        "flavor_profile": "Ripe dark plum, cinnamon spice, syrupy molasses, and lingering cocoa.",
        "description": "Rare shade-grown coffee cultivated in the mist-shrouded Toraja highlands of Sulawesi. Renowned for its smooth, heavy body and sweet herbal finish.",
    },
    {
        "id": 18,
        "name": "Espresso Roast Coffee (8oz)",
        "slug": "espresso-roast",
        "pack_size": "8oz",
        "category_name": "Dark & Distinctive",
        "category_slug": "dark-distinctive",
        "source_url": "https://www.coffeebean.pk/product/espresso-roast-coffee/",
        "image_url": "https://www.coffeebean.pk/wp-content/uploads/2017/10/Espresso-Roast-Coffee-8oz-550x550.jpg",
        "local_image": "/products/coffee/espresso-roast.jpg",
        "filename": "espresso-roast.jpg",
        "roast_level": "Dark Roast",
        "origin": "Handcrafted Espresso Blend",
        "flavor_profile": "Bittersweet chocolate, caramelized sugar, and thick syrupy crema.",
        "description": "The master blend at the heart of every handcrafted espresso beverage served at The Coffee Bean & Tea Leaf worldwide. Roasted dark to produce rich, velvety crema.",
    },
]

def run_download_and_seed():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    public_coffee_dir = os.path.join(base_dir, "..", "public", "products", "coffee")
    os.makedirs(public_coffee_dir, exist_ok=True)
    
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    
    print(f"Target directory for images: {public_coffee_dir}")
    for p in PRODUCTS:
        target_path = os.path.join(public_coffee_dir, p["filename"])
        if not os.path.exists(target_path) or os.path.getsize(target_path) < 100:
            print(f"Downloading image: {p['image_url']} -> {target_path}")
            try:
                req = urllib.request.Request(p["image_url"], headers=headers)
                with urllib.request.urlopen(req, context=ssl_context, timeout=20) as resp:
                    data = resp.read()
                    with open(target_path, "wb") as f:
                        f.write(data)
                print(f"Saved {p['filename']} ({len(data)} bytes)")
            except Exception as e:
                print(f"Download failed for {p['filename']}: {e}")
        else:
            print(f"Existing file verified: {p['filename']} ({os.path.getsize(target_path)} bytes)")

    print("\nAll 18 images checked successfully.")

if __name__ == "__main__":
    run_download_and_seed()
